### ISSUE TITLE
Invalid injection configuration

### ISSUE THREAD

**Issue by gallandarakhneorg** [janus-project/janusproject#115]
When launching the Jaak ant-colony demo, the following error occurs:
```
INFOS: Lancement de l'agent : io.sarl.jaak.demos.ants.Ant
Erreur lors du lancement de Janus : Impossible d'instancier un agent de type class io.sarl.jaak.demos.ants.Ant à cause de: Guice configuration errors:

1) Could not find a suitable constructor in java.util.UUID. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at java.util.UUID.class(UUID.java:70)
  while locating java.util.UUID
    for parameter 1 at io.sarl.jaak.demos.ants.Ant.<init>(Ant.java:180)
  while locating io.sarl.jaak.demos.ants.Ant

2) Could not find a suitable constructor in java.util.UUID. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at java.util.UUID.class(UUID.java:70)
  while locating java.util.UUID
    for parameter 2 at io.sarl.jaak.demos.ants.Ant.<init>(Ant.java:180)
  while locating io.sarl.jaak.demos.ants.Ant

2 errors"
io.janusproject.kernel.services.jdk.spawn.StandardSpawnService$CannotSpawnException: Impossible d'instancier un agent de type class io.sarl.jaak.demos.ants.Ant à cause de: Guice configuration errors:

1) Could not find a suitable constructor in java.util.UUID. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at java.util.UUID.class(UUID.java:70)
  while locating java.util.UUID
    for parameter 1 at io.sarl.jaak.demos.ants.Ant.<init>(Ant.java:180)
  while locating io.sarl.jaak.demos.ants.Ant

2) Could not find a suitable constructor in java.util.UUID. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at java.util.UUID.class(UUID.java:70)
  while locating java.util.UUID
    for parameter 2 at io.sarl.jaak.demos.ants.Ant.<init>(Ant.java:180)
  while locating io.sarl.jaak.demos.ants.Ant

2 errors
	at io.janusproject.kernel.services.jdk.spawn.StandardSpawnService.spawn(StandardSpawnService.java:113)
	at io.janusproject.kernel.Kernel.spawn(Kernel.java:142)
	at io.janusproject.Boot.startJanus(Boot.java:681)
	at io.janusproject.Boot.startJanus(Boot.java:640)
	at io.janusproject.Boot.main(Boot.java:257)
Caused by: com.google.inject.ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in java.util.UUID. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at java.util.UUID.class(UUID.java:70)
  while locating java.util.UUID
    for parameter 1 at io.sarl.jaak.demos.ants.Ant.<init>(Ant.java:180)
  while locating io.sarl.jaak.demos.ants.Ant

2) Could not find a suitable constructor in java.util.UUID. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at java.util.UUID.class(UUID.java:70)
  while locating java.util.UUID
    for parameter 2 at io.sarl.jaak.demos.ants.Ant.<init>(Ant.java:180)
  while locating io.sarl.jaak.demos.ants.Ant

2 errors
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1042)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1001)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at io.janusproject.kernel.services.jdk.spawn.StandardSpawnService.spawn(StandardSpawnService.java:107)
	... 4 more
```

**Comment by gallandarakhneorg** [comment]
The problem is due to an agent type (class file) that was generated for a version of the API too old: the constructor prototype is not the correct one.
