### ISSUE TITLE
NPE in the context manager

### ISSUE THREAD

**Issue by gallandarakhneorg** [janus-project/janusproject#99]
```
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMM$77777777777777777777777777NMMMMMM
MMMM$77777$ZO8OO7777$77777777777777OMMMM
MM77MMMMMMMMMMMM7777MMMZ777$MMMMN7777MMM
MMMMMMMMMMMMMMMM777NMMN77778MMMMMM777ZMM
MMMMMMMMMMMMMMMO77OMMM$7777MMMMMMMD777MM
MMMMMMMMMMMMMMN777MMMM7777NMMMMMMMN777MM
MMMMMMMMMMMMMMO777MMMM7777MMMMMMMMO777MM
MMMMMMMMMMMMMM$77$MMMD7777MMMMMMMM7777MM
MMMMMMMMMMMMMM777DMMM$777$MMMMMMZ7777MMM
MMMMMMMMMMNDO$777ZZZZ7777$$777777777MMMM
MMMMMD777777777777777777777777777$MMMMMM
MMMM77777777777777777777777777$8MMMMMMMM
MM77777$NMMMM777NMMMO7778MMMMMMMMMMMMMMM
M$77ZMMMMMMMM777MMMMZ777MMMMMMMMMMMMMMMM
M77ZMMMMMMMM8777MMMM777ZMMMMMMMMMMMMMMMM
877NMMMMMMMM7778MMMM77DMMMMMMMMMMMMMMMMM
877DMMMMMMMN77ZMMMMO7$MMMMMMMMMMMMMMMMMM
M777NMMMMN7777MMMMZ7DMMMM777MMMMMMMMMMMM
MM777777777$MMMMMZMMMMMM$777MMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
janv. 12, 2015 10:50:08 AM null
INFOS: [LOCAL] [dev] [3.4-EA] Picking address configured by property 'hazelcast.local.localAddress'
janv. 12, 2015 10:50:08 AM null
INFOS: [LOCAL] [dev] [3.4-EA] Picked Address[10.85.0.243]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
janv. 12, 2015 10:50:08 AM null
INFOS: [10.85.0.243]:5701 [dev] [3.4-EA] Starting with 4 generic operation threads and 8 partition operation threads.
janv. 12, 2015 10:50:08 AM null
INFOS: [10.85.0.243]:5701 [dev] [3.4-EA] Hazelcast 3.4-EA (20141104 - c0e3d4a) starting at Address[10.85.0.243]:5701
janv. 12, 2015 10:50:08 AM null
INFOS: [10.85.0.243]:5701 [dev] [3.4-EA] Copyright (C) 2008-2014 Hazelcast.com
janv. 12, 2015 10:50:08 AM null
INFOS: [10.85.0.243]:5701 [dev] [3.4-EA] Creating MulticastJoiner
janv. 12, 2015 10:50:08 AM null
INFOS: [10.85.0.243]:5701 [dev] [3.4-EA] Address[10.85.0.243]:5701 is STARTING
janv. 12, 2015 10:50:08 AM null
INFOS: [10.85.0.243]:5701 [dev] [3.4-EA] Trying to join to discovered node: Address[10.85.0.237]:5701
janv. 12, 2015 10:50:08 AM null
INFOS: [10.85.0.243]:5701 [dev] [3.4-EA] Connecting to /10.85.0.237:5701, timeout: 0, bind-any: true
janv. 12, 2015 10:50:09 AM null
INFOS: [10.85.0.243]:5701 [dev] [3.4-EA] Established socket connection between /10.85.0.243:51082 and /10.85.0.237:5701
janv. 12, 2015 10:50:16 AM null
INFOS: [10.85.0.243]:5701 [dev] [3.4-EA] 

Members [2] {
Member [10.85.0.237]:5701
Member [10.85.0.243]:5701 this
}

janv. 12, 2015 10:50:18 AM null
INFOS: [10.85.0.243]:5701 [dev] [3.4-EA] Address[10.85.0.243]:5701 is STARTED
janv. 12, 2015 10:50:18 AM null
INFOS: Contexte d'agent créé : c3315f1e-90ee-4ed0-868a-ce86a072aa7f
janv. 12, 2015 10:50:18 AM null
INFOS: Espace créé : SpaceID [id=7ba8885d-545b-445a-a0e9-b655bc15ebe0, contextID=c3315f1e-90ee-4ed0-868a-ce86a072aa7f, spaceSpec=interface io.sarl.util.OpenEventSpaceSpecification]
janv. 12, 2015 10:50:18 AM com.google.common.util.concurrent.ServiceManager
GRAVE: Service StandardContextSpaceService [FAILED] has failed in the STARTING state.
java.lang.NullPointerException
at io.janusproject.kernel.services.jdk.contextspace.StandardContextSpaceService.createContext(StandardContextSpaceService.java:215)
at io.janusproject.kernel.services.jdk.contextspace.StandardContextSpaceService.ensureDefaultSpaceDefinition(StandardContextSpaceService.java:355)
at io.janusproject.kernel.services.jdk.contextspace.StandardContextSpaceService.doStart(StandardContextSpaceService.java:375)
at com.google.common.util.concurrent.AbstractService.startAsync(AbstractService.java:174)
at io.janusproject.services.Services$StartingPhaseAccessors.run(Services.java:430)
at io.janusproject.services.Services.runDependencyGraph(Services.java:308)
at io.janusproject.services.Services.startServices(Services.java:82)
at io.janusproject.kernel.Kernel.<init>(Kernel.java:111)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at com.google.inject.internal.DefaultConstructionProxyFactory$2.newInstance(DefaultConstructionProxyFactory.java:86)
at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:108)
at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:88)
at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:269)
at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1066)
at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
at com.google.inject.Scopes$1$1.get(Scopes.java:65)
at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1009)
at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1059)
at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1005)
at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1044)
at io.janusproject.kernel.Kernel.create(Kernel.java:121)
at io.janusproject.Boot.startJanus(Boot.java:653)
at io.janusproject.Boot.startJanus(Boot.java:617)
at io.janusproject.Boot.main(Boot.java:253)
```

**Comment by gallandarakhneorg** [comment]
I cannot reproduce this error. Indeed, the statement line 215 is:
```java
this.contexts.put(contextID, ctx);
```

The local variables `contextID` and `ctx` should not be `null` since they are tested with assertions.
The attribute `contexts` is never reset to `null`.

If not already done, please activate the assertions in your JVM (`-ea`), and give us a feedback.
